### ISSUE TITLE
Medium Error: If specified, publishedAt must be in the past. (2014) 

### ISSUE THREAD

**Issue by koffisani** [Medium/medium-wordpress-plugin#106]
I'm using WP 4.5.2 and facing this issue when posting my articles.

> Medium Error: If specified, publishedAt must be in the past. (2014) 

 Is it a bug ?

**Comment by huckphin** [comment]
Hello @koffisani: There is not a known issue at this time. Can I get the following information from you to help debug? May I ask you to attempt to cross-post again, and provide me with the following information?

Medium Username, DateTime that you tried to cross-post (including the time zone), the TimeZone your WordPress installation is set to.

From there, I can inspect the logs, and learn more information about this. Thanks!

**Comment by koffisani** [comment]
Hello @huckphin, sorry for my silence. See bellow the informations you requested :
Medium username : @koffisani
DateTime I tried to cross-post : 2016-07-26 19 : 14 GMT+1
DateTime of my WP : 2016-07-26 20 :14 GMT+2 [Paris/France]

[Screen shot](https://goo.gl/photos/tUoj4A9dU86pwL3g6)
Thanks.

**Comment by huckphin** [comment]
No worries. Thank you for providing that information! That helped me track down the actual issue. For the actual details, the post that you provided failed to post because your server is thirteen seconds ahead of our server, which is *technically* in the future. This was very helpful. Thank you for reaching back out to us.

I should have time this week to put in a fix.

**Comment by koffisani** [comment]
Hi @huckphin. Is it right now ? I think itsn't solved.

**Comment by jan-vandenberg** [comment]
I **just** had this very same error.

**Comment by vovafeldman** [comment]
@huckphin I think that the plugin doesn't take WP timezone (set in the settings) into consideration when preparing the publication date for Medium. I was getting the error from a server with a properly synced clock. After changing the timezone to UTC in the WP Admin -> Settings -> General, it started working.
