### ISSUE TITLE
Canonicals

### ISSUE THREAD

**Issue by wlmmatt** [Medium/medium-wordpress-plugin#11]
Not sure this version is setting up canonicals correctly. Canonicals appear at both ends pointing to self rather than Medium pointing back toward the source WP permalink.

**Comment by majelbstoat** [comment]
Hi @winmatt, I can't reproduce this. The code appears to clearly append the WP permalink to the end of a Medium post. However, it is possible that the permalink is empty, which would give the impression of it linking to itself. Can you send me a link to a Medium post that is linked incorrectly?

**Comment by wlmmatt** [comment]
Hi Jamie

Sorry - I didn’t present that clearly.

Here are my test posts on wp (http://readpoppy.com/phase2/?p=31) and on medium (https://medium.com/@WLMmatt/ab78d1ec1d11).

Yes, the links at the end point to each other so when you click, you get to the right place *however* the problem is the canonicals defined in the headers rather thank the hyperlinks.

On Medium, the canonical link points to Medium: "<link rel="canonical" href="https://medium.com/@WLMmatt/ab78d1ec1d11”>”

On Wordpress, the canonical link points to Wordpress: "<link rel='canonical' href='http://readpoppy.com/phase2/?p=31' />”

If I understand canonicals correctly and if we are taking the Wordpress post as the origin, we need the Medium post to point to WP in the header and the Wordpress post shouldn’t have any canonical link (it may not harm to have it but it doesn’t need to be there).

Does that help?

Matt

**Comment by majelbstoat** [comment]
Ah, I see. That makes sense. Yes, I think you're right, the WP post should be the canonical one in this case. FWIW, the plugin doesn't touch the canonical link on your own blog, so I think that's just WP putting it in there for you.

Ok, I'll see about fixing this! :)

**Comment by wlmmatt** [comment]
Oh that’s interesting - will need to see if that’s a core thing or something to do with the theme we’re using.

Thanks for the update!

Matt
