### ISSUE TITLE
Publish to Plugin Directory 

### ISSUE THREAD

**Issue by stopsatgreen** [Medium/medium-wordpress-plugin#12]
Has this already been pushed to the Wordpress Plugin Directory? Can’t find it there. If not, would be better published there, to more easily receive updates.

**Comment by majelbstoat** [comment]
It has been submitted to the db, and we are awaiting review. If/when that happens, we will abide by the rules and host the code in the svn repo. Haven't figured out the full workflow yet, but we'll probably still do active development here, then ship tagged builds to the svn repo.

Closing for now.
