### ISSUE TITLE
Admin screen does not appear after installation

### ISSUE THREAD

**Issue by DanielGenser** [Medium/medium-wordpress-plugin#13]
I've uploaded and successfully activated the plugin in my WP installation, but there appears to be no Medium admin panel available.
![screenshot 2015-10-08 15 07 35](https://cloud.githubusercontent.com/assets/2189155/10367044/6e9cf626-6dce-11e5-861d-ec892952c75d.png)

**Comment by ThemeSurgeon** [comment]
That's because the settings are in your user profile.

**Comment by DanielGenser** [comment]
Ah!

On Thursday, October 8, 2015, John Teague <notifications@github.com> wrote:

> That's because the settings are in your user profile.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Medium/medium-wordpress-plugin/issues/13#issuecomment-146615346>
> .
>


-- 
--
Daniel Genser
Probably typed on a ferry.
