### ISSUE TITLE
Cannot use constants as the textdomain parameter in translation functions

### ISSUE THREAD

**Issue by fjarrett** [Medium/medium-wordpress-plugin#14]
POT files are generated from the source files themselves, [the PHP is not parsed](https://markjaquith.wordpress.com/2011/10/06/translating-wordpress-plugins-and-themes-dont-get-clever/), so the textdomain must be a string literal to be GNU gettext compatible.

**INCORRECT**
```php
<?php _e( 'Test', MEDIUM_TEXTDOMAIN ); ?>
```

**CORRECT**
```php
<?php _e( 'Test', 'medium' ); ?>
```

**Comment by majelbstoat** [comment]
Ugh, I used to know this. Has been too long. Thanks!

**Comment by fjarrett** [comment]
@majelbstoat No problem!
