### ISSUE TITLE
Consider moving to the GPLv3 license

### ISSUE THREAD

**Issue by fjarrett** [Medium/medium-wordpress-plugin#16]
While the Apache License 2.0 [is considered](http://www.apache.org/licenses/GPL-compatibility.html) to be GPL 3.0 compatible, it would be more straightforward to just license the plugin as GPL 3.0 since that is the standard defined and required by the WordPress open source project itself.

You also won't be able to submit this to the WordPress.org plugin repository (#12) unless it is explicitly licensed as GPLv2 or later.

https://wordpress.org/about/license/

**Comment by ThemeSurgeon** [comment]
I second that recommendation. Would be better to submit the plugin through regular WordPress.org repo for maximum exposure.

**Comment by majelbstoat** [comment]
We'll chat about this. The plugin has already been submitted to the WP Plugins DB, and is awaiting review.

FWIW, the licensing rules for that state: "Your plugin must be **compatible** with the GNU General Public License v2, or any later version."

https://wordpress.org/plugins/about/

**Comment by ThemeSurgeon** [comment]
Thanks Jamie - I am doing a little work on a couple of things that I think
will make it easier to get approved by the plugin review team, assuming you
are good with that.

Best to you and yours,

John

John Teague
Founder
Theme Surgeons LLC
john@themesurgeons.com
https://themesurgeons.com

On Twitter <https://twitter.com/themeSurgeon> | Google+
<https://plus.google.com/+ThemesurgeonsWordPress/>

**Comment by fjarrett** [comment]
Thanks for your consideration, @majelbstoat. Yeah, you are right, I just found [this post](https://make.wordpress.org/core/2012/04/30/the-plugin-directorys-licensing-guidelines-have-been-updated/).

So if you have an internal reason for using Apache 2.0, this is apparently fine to do, and it looks like you can be published into WordPress.org repo.

However, if there's no specific reason for choosing this one, then I suppose my suggestion here is just to use the more straightforward license used by the parent project.

Thanks!

**Comment by sagudo** [comment]
cc @feerst

**Comment by majelbstoat** [comment]
Having spoken with legal, and having confirmed with a reviewer at WP, for simplicity's sake, we're going to stay with Apache 2, in line with our other open source work. Appreciate your consideration.
