### ISSUE TITLE
Clarity on the spelling and definition of "cross" terms used

### ISSUE THREAD

**Issue by fjarrett** [Medium/medium-wordpress-plugin#22]
* cross-post
 * crosspost
 * cross-link
 * crosslink

1. I've noticed these terms spelled both with and without the dash, which way is preferred?

2. And what is the difference between cross-posting and cross-linking?

**Comment by majelbstoat** [comment]
Yah, I was sloppy here. Going to standardise on "cross-post" and "cross-link". Cross-post refers to the act of creating a post on Medium. Cross-link refers to whether you want a link to be appended on both sites that point to each other.

**Comment by fjarrett** [comment]
Thanks!
