### ISSUE TITLE
Plugin attempts to cross-post new pages

### ISSUE THREAD

**Issue by demifiend** [Medium/medium-wordpress-plugin#23]
I added a Page (not a Post) to my site, and the Plugin pushed it to Medium. Saving changes to a Menu also resulted in an attempted push to Medium. Neither of these events should happen; or, at least there should be a switch to control whether Pages get cross-posted.

**Comment by fjarrett** [comment]
Whoa, yeah this is kind of related to #17 as well, at least the part about pushing to Medium without explicitly telling it to.
