### ISSUE TITLE
the_excerpt() function breaks when a post has Also Published on Medium appended to the post

### ISSUE THREAD

**Issue by rjmccollam** [Medium/medium-wordpress-plugin#32]
I just noticed that all posts that have the Also Published on Medium appended to the end of the post display the full contents of a post when `the_excerpt()` is called in a theme.

Examples of this on my blog page at http://rjmccollam.com/blog/

**Comment by majelbstoat** [comment]
Thanks @rjmccollam, we'll look into this.

**Comment by majelbstoat** [comment]
Should be fixed, please check out the latest version and let me know.

**Comment by rjmccollam** [comment]
Yep, this fixes it.

Well done guys.
