### ISSUE TITLE
The medium.zip file doesn't contain a complete copy of the plugin

### ISSUE THREAD

**Issue by Japh** [Medium/medium-wordpress-plugin#9]
To be honest, the medium.zip file is kind of redundant, but if you really want it there it should probably contain a complete copy of the plugin  :wink: 

I'd probably suggest removing it entirely, and users can either clone the repo, or use the GitHub "Download ZIP" button.

**Comment by majelbstoat** [comment]
I needed the zip file only to have a convenient place for the initial submission to wordpress' plugin db. It won't live there very long :)

**Comment by majelbstoat** [comment]
(It should have everything in it though... what's missing)

**Comment by majelbstoat** [comment]
Fixed in #18.

**Comment by Japh** [comment]
Thanks for removing it! Much simpler now :)
It was missing at least all files from `lib`.

Thanks again for this plugin!
